### PR TITLE
Add upload folder name

### PR DESCRIPTION
**Pull request by fengerzh**
Hi, there, for better control and management, it's better to have a folder setting for uploading, so the screenshot pictures uploaded to cloudinary won't mix with other pictures.

### CODE REVIEW

**Comment by urre** [comment]
Hey, you can set pathname and filename like this in the `.env` file:

```
PATHNAME="/users/myusername/dropbox/screenshots/"
FILENAME="screenshot.jpg"
```

There will always just be one local file `screenshot.jpg`, then it is uploaded to cloudinary

**Comment by fengerzh** [comment]
No, that's for local path. I mean when upload to Cloudinary, cloudinary also have their own folder name, like this:

image

**Comment by urre** [comment]
@fengerzh ah, sorry. You meant in Cloudinary

**Comment by urre** [comment]
Thanks! @fengerzh

**Pull request merged**
